package de.zpid.datawiz.enumeration;

public enum DataWizErrorCodes {
  OK,
  SESSION_ERROR,
  DATABASE_ERROR,
  RECORD_SAVE_ERROR,
  NO_DATA_ERROR,
  MINIO_SAVE_ERROR,
  MINIO_READ_ERROR,
  MINIO_DELETE_ERROR,
  MISSING_PID_ERROR,
  MISSING_UID_ERROR,
  MISSING_STUDYID_ERROR,
  PROJECT_NOT_AVAILABLE,
  STUDY_NOT_AVAILABLE,
  STUDY_DELETE_ERROR,
  RECORD_NOT_AVAILABLE,
  RECORD_PARSING_ERROR,
  RECORD_VALIDATION_ERROR,
  DMP_VALIDATION_ERROR,
  RECORD_DELETE_ERROR,
  IMPORT_TYPE_NOT_SUPPORTED,
  DATE_PARSING_ERROR,  
  IMPORT_FILE_IS_EMPTY,
  USER_ACCESS_PROJECT_PERMITTED,
	USER_ACCESS_STUDY_PERMITTED,
	USER_ACCESS_RECORD_PERMITTED;
}
