package de.zpid.datawiz.enumeration;

public enum DWFieldTypes {
  DATATYPE,
  COLLECTIONMODE,
  METAPORPOSE,
  DATAFORMAT,
  SOFTWARE,
  PUBONDATA,
  OBJECTIVES,
  CONFLINTEREST,
  RELTHEORY,
  MEASOCCNAME,
  INTERARMS,
  ELIGIBILITY
}
