package de.zpid.datawiz.enumeration;

public enum ExportStates {

  PROJECT_EXPORT_FULL,
  PROJECT_EXPORT_METADATA,
  PROJECT_EXPORT_DMP,
  PROJECT_EXPORT_MATERIAL,
  STUDY_EXPORT_FULL,
  STUDY_EXPORT_METADATA,
  STUDY_EXPORT_MATERIAL,
  RECORD_EXPORT_FULL,
  RECORD_EXPORT_METADATA,
  RECORD_EXPORT_CODEBOOK,
  RECORD_EXPORT_MATRIX;

}
