package de.zpid.datawiz.enumeration;

public enum InterventionTypes {
  QUASIEXPERIMENTAL,
  REPEATEDMEASURES,
  GROUPCOMPARISON,
  MIXEDDESIGN,
  LABORATORY,
  FIELD,
  RANDOMIZED,
  NOTRANDOMIZED,
  HARDLYINSTRUMENT,
  PARTIALLYINSTRUMENT,
  FULLYINSTRUMENT
}
